languageCode: "en-us"
baseUrl: "http://localhost:1313"
title: "E-Heza Documentation"
outputs:
frontmatter:
  date:
    - ":filename"
    - ":default"
  lastmod:
    - "lastmod"
    - ":git"
    - "date"
    - "publishDate"
markup:
  goldmark:
    renderer:
      unsafe: true
enableGitInfo: true
