---
label: Doc Page
hide_body: false
fields:
- type: text
  name: section
  label: section
- type: text
  name: subsection
  label: subsection
- type: text
  name: title
  label: title
- type: number
  name: weight
  label: weight
pages:
- content/user_docs/anc-progress-report-chw.md
- content/user_docs/decision-support-and-next-step-guidance-1.md
- content/user_docs/decision-support-and-next-step-guidance-antenatal-care.md
- content/user_docs/decision-support-and-next-step-guidance.md
- content/user_docs/laboratory-with-pending-results-management.md
