---
label: Doc Page
hide_body: false
fields:
- type: text
  name: section
  label: section
- type: text
  name: subsection
  label: subsection
- type: text
  name: title
  label: title
- type: number
  name: weight
  label: weight
