---
label: Doc Page
hide_body: false
fields:
- type: text
  name: section
  label: section
- type: text
  name: title
  label: title
pages:
- content/docs/chw-newborn-exam.md
- content/docs/chw-nutrition.md
