---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: index.md
  label: Home page
  match: "**/*"
- type: directory
  path: content/developer_docs
  label: Developer Documentation
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - doc-page
- type: directory
  path: content/community_docs
  label: Community Documentation
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - doc-page
- type: directory
  path: content/admin_docs
  label: Admin Documentation
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - doc-page
- type: directory
  path: content/user_docs
  label: User Documentation
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - doc-page
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.76.5
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.76.5
