---
label: Doc Page
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: section
  label: section
pages:
- content/docs/acute-illness-module.md
- content/docs/antenatal-care-module.md
- content/docs/delete-a-person-relationship-group.md
- content/docs/importing-patient-data-in-bulk-backend.md
